apiVersion: v1
kind: Service
metadata:
  name: decision-service
  labels:
    operation: loadBalancerService
spec:
  type: LoadBalancer
  selector:
    app: decision-service-pod
  ports:
    - port: 80
      targetPort: 2212